CREATE TABLE languages (
    id INT AUTO_INCREMENT PRIMARY KEY,
    iso_639_1 VARCHAR(2) UNIQUE NOT NULL,
    name_fr VARCHAR(255) NOT NULL,
    name_en VARCHAR(255) NOT NULL
);

INSERT INTO languages (iso_639_1, name_fr, name_en) VALUES
('aa', 'afar', 'Afar'),
('ab', 'abkhaze', 'Abkhazian'),
('ae', 'avestique', 'Avestan'),
('af', 'afrikaans', 'Afrikaans'),
('ak', 'akan', 'Akan'),
('am', 'amharique', 'Amharic'),
('an', 'aragonais', 'Aragonese'),
('ar', 'arabe', 'Arabic'),
('as', 'assamais', 'Assamese'),
('av', 'avar', 'Avaric'),
('ay', 'aymara', 'Aymara'),
('az', 'azéri', 'Azerbaijani'),
('ba', 'bachkir', 'Bashkir'),
('be', 'biélorusse', 'Belarusian'),
('bg', 'bulgare', 'Bulgarian'),
('bh', 'bihari', 'Bihari'),
('bi', 'bichlamar', 'Bislama'),
('bm', 'bambara', 'Bambara'),
('bn', 'bengali', 'Bengali'),
('bo', 'tibétain', 'Tibetan'),
('br', 'breton', 'Breton'),
('bs', 'bosniaque', 'Bosnian'),
('ca', 'catalan', 'Catalan'),
('ce', 'tchétchène', 'Chechen'),
('ch', 'chamorro', 'Chamorro'),
('co', 'corse', 'Corsican'),
('cr', 'cri', 'Cree'),
('cs', 'tchèque', 'Czech'),
('cu', 'vieux slave', 'Old Church Slavonic'),
('cv', 'tchouvache', 'Chuvash'),
('cy', 'gallois', 'Welsh'),
('da', 'danois', 'Danish'),
('de', 'allemand', 'German'),
('dv', 'divhehi', 'Divehi'),
('dz', 'dzongkha', 'Dzongkha'),
('ee', 'éwé', 'Ewe'),
('el', 'grec', 'Greek'),
('en', 'anglais', 'English'),
('eo', 'espéranto', 'Esperanto'),
('es', 'espagnol', 'Spanish'),
('et', 'estonien', 'Estonian'),
('eu', 'basque', 'Basque'),
('fa', 'persan', 'Persian'),
('ff', 'peul', 'Fulah'),
('fi', 'finnois', 'Finnish'),
('fj', 'fidjien', 'Fijian'),
('fo', 'féroïen', 'Faroese'),
('fr', 'français', 'French'),
('fy', 'frison', 'Western Frisian'),
('ga', 'irlandais', 'Irish'),
('gd', 'gaélique écossais', 'Scottish Gaelic'),
('gl', 'galicien', 'Galician'),
('gn', 'guarani', 'Guarani'),
('gu', 'goudjrati', 'Gujarati'),
('gv', 'manx', 'Manx'),
('ha', 'haoussa', 'Hausa'),
('he', 'hébreu', 'Hebrew'),
('hi', 'hindi', 'Hindi'),
('ho', 'hiri motou', 'Hiri Motu'),
('hr', 'croate', 'Croatian'),
('ht', 'créole haïtien', 'Haitian Creole'),
('hu', 'hongrois', 'Hungarian'),
('hy', 'arménien', 'Armenian'),
('hz', 'héréro', 'Herero'),
('ia', 'interlingua', 'Interlingua'),
('id', 'indonésien', 'Indonesian'),
('ie', 'interlingue', 'Interlingue'),
('ig', 'igbo', 'Igbo'),
('ii', 'yi du sichuan', 'Nuosu'),
('ik', 'inupiaq', 'Inupiaq'),
('io', 'ido', 'Ido'),
('is', 'islandais', 'Icelandic'),
('it', 'italien', 'Italian'),
('iu', 'inuktitut', 'Inuktitut'),
('ja', 'japonais', 'Japanese'),
('jv', 'javanais', 'Javanese'),
('ka', 'géorgien', 'Georgian'),
('kg', 'kikongo', 'Kongo'),
('ki', 'kikuyu', 'Kikuyu'),
('kj', 'kuanyama', 'Kwanyama'),
('kk', 'kazakh', 'Kazakh'),
('kl', 'groenlandais', 'Greenlandic'),
('km', 'khmer central', 'Khmer'),
('kn', 'kannada', 'Kannada'),
('ko', 'coréen', 'Korean'),
('kr', 'kanouri', 'Kanuri'),
('ks', 'kashmiri', 'Kashmiri'),
('ku', 'kurde', 'Kurdish'),
('kv', 'komi', 'Komi'),
('kw', 'cornique', 'Cornish'),
('ky', 'kirghize', 'Kyrgyz'),
('la', 'latin', 'Latin'),
('lb', 'luxembourgeois', 'Luxembourgish'),
('lg', 'ganda', 'Ganda'),
('li', 'limbourgeois', 'Limburgish'),
('ln', 'lingala', 'Lingala'),
('lo', 'lao', 'Lao'),
('lt', 'lituanien', 'Lithuanian'),
('lu', 'luba-katanga', 'Luba-Katanga'),
('lv', 'letton', 'Latvian'),
('mg', 'malgache', 'Malagasy'),
('mh', 'marshallais', 'Marshallese'),
('mi', 'maori', 'Māori'),
('mk', 'macédonien', 'Macedonian'),
('ml', 'malayalam', 'Malayalam'),
('mn', 'mongol', 'Mongolian'),
('mo', 'moldave', 'Moldovan'),
('mr', 'marathe', 'Marathi'),
('ms', 'malais', 'Malay'),
('mt', 'maltais', 'Maltese'),
('my', 'birman', 'Burmese'),
('na', 'nauruan', 'Nauruan'),
('nb', 'norvégien bokmål', 'Norwegian Bokmål'),
('nd', 'ndébélé du Nord', 'Northern Ndebele'),
('ne', 'népalais', 'Nepali'),
('ng', 'ndonga', 'Ndonga'),
('nl', 'néerlandais', 'Dutch'),
('nn', 'norvégien nynorsk', 'Norwegian Nynorsk'),
('no', 'norvégien', 'Norwegian'),
('nr', 'ndébélé du Sud', 'Southern Ndebele'),
('nv', 'navaho', 'Navajo'),
('ny', 'nyanja', 'Chichewa'),
('oc', 'occitan', 'Occitan'),
('oj', 'ojibwa', 'Ojibwe'),
('om', 'oromo', 'Oromo'),
('or', 'oriya', 'Oriya'),
('os', 'ossète', 'Ossetian'),
('pa', 'pendjabi', 'Punjabi'),
('pi', 'pali', 'Pāli'),
('pl', 'polonais', 'Polish'),
('ps', 'pachto', 'Pashto'),
('pt', 'portugais', 'Portuguese'),
('qu', 'quechua', 'Quechua'),
('rm', 'romanche', 'Romansh'),
('rn', 'kirundi', 'Kirundi'),
('ro', 'roumain', 'Romanian'),
('ru', 'russe', 'Russian'),
('rw', 'rwanda', 'Kinyarwanda'),
('sa', 'sanskrit', 'Sanskrit'),
('sc', 'sarde', 'Sardinian'),
('sd', 'sindhi', 'Sindhi'),
('se', 'sami du Nord', 'Northern Sami'),
('sg', 'sango', 'Sango'),
('sh', 'serbo-croate', 'Serbo-Croatian'),
('si', 'cinghalais', 'Sinhalese'),
('sk', 'slovaque', 'Slovak'),
('sl', 'slovène', 'Slovenian'),
('sm', 'samoan', 'Samoan'),
('sn', 'shona', 'Shona'),
('so', 'somali', 'Somali'),
('sq', 'albanais', 'Albanian'),
('sr', 'serbe', 'Serbian'),
('ss', 'swati', 'Swati'),
('st', 'soto du Sud', 'Southern Sotho'),
('su', 'soundanais', 'Sundanese'),
('sv', 'suédois', 'Swedish'),
('sw', 'swahili', 'Swahili'),
('ta', 'tamoul', 'Tamil'),
('te', 'télougou', 'Telugu'),
('tg', 'tadjik', 'Tajik'),
('th', 'thaï', 'Thai'),
('ti', 'tigrigna', 'Tigrinya'),
('tk', 'turkmène', 'Turkmen'),
('tl', 'tagalog', 'Tagalog'),
('tn', 'tswana', 'Tswana'),
('to', 'tongien', 'Tongan'),
('tr', 'turc', 'Turkish'),
('ts', 'tsonga', 'Tsonga'),
('tt', 'tatar', 'Tatar'),
('tw', 'twi', 'Twi'),
('ty', 'tahitien', 'Tahitian'),
('ug', 'ouïgour', 'Uighur'),
('uk', 'ukrainien', 'Ukrainian'),
('ur', 'ourdou', 'Urdu'),
('uz', 'ouzbek', 'Uzbek'),
('ve', 'venda', 'Venda'),
('vi', 'vietnamien', 'Vietnamese'),
('vo', 'volapük', 'Volapük'),
('wa', 'wallon', 'Walloon'),
('wo', 'wolof', 'Wolof'),
('xh', 'xhosa', 'Xhosa'),
('yi', 'yiddish', 'Yiddish'),
('yo', 'yoruba', 'Yoruba'),
('za', 'zhuang', 'Zhuang'),
('zh', 'chinois', 'Chinese'),
('zu', 'zoulou', 'Zulu');

CREATE TABLE IF NOT EXISTS countries (
    id INT AUTO_INCREMENT PRIMARY KEY,
    iso_3166_1 VARCHAR(2) UNIQUE,
    name_fr VARCHAR(255),
    name_en VARCHAR(255)
);

-- Insertion des données dans la table countries
INSERT INTO countries (iso_3166_1, name_fr, name_en) VALUES
('AD', 'Andorre', 'Andorra'),
('AE', 'Émirats Arabes Unis', 'United Arab Emirates'),
('AF', 'Afghanistan', 'Afghanistan'),
('AG', 'Antigua-et-Barbuda', 'Antigua and Barbuda'),
('AI', 'Anguilla', 'Anguilla'),
('AL', 'Albanie', 'Albania'),
('AM', 'Arménie', 'Armenia'),
('AO', 'Angola', 'Angola'),
('AQ', 'Antarctique', 'Antarctica'),
('AR', 'Argentine', 'Argentina'),
('AS', 'Samoa Américaines', 'American Samoa'),
('AT', 'Autriche', 'Austria'),
('AU', 'Australie', 'Australia'),
('AW', 'Aruba', 'Aruba'),
('AX', 'Îles Åland', 'Åland Islands'),
('AZ', 'Azerbaïdjan', 'Azerbaijan'),
('BA', 'Bosnie-Herzégovine', 'Bosnia and Herzegovina'),
('BB', 'Barbade', 'Barbados'),
('BD', 'Bangladesh', 'Bangladesh'),
('BE', 'Belgique', 'Belgium'),
('BF', 'Burkina Faso', 'Burkina Faso'),
('BG', 'Bulgarie', 'Bulgaria'),
('BH', 'Bahreïn', 'Bahrain'),
('BI', 'Burundi', 'Burundi'),
('BJ', 'Bénin', 'Benin'),
('BL', 'Saint-Barthélemy', 'Saint Barthélemy'),
('BM', 'Bermudes', 'Bermuda'),
('BN', 'Brunei', 'Brunei Darussalam'),
('BO', 'Bolivie', 'Bolivia'),
('BQ', 'Bonaire, Saint-Eustache et Saba', 'Bonaire, Sint Eustatius and Saba'),
('BR', 'Brésil', 'Brazil'),
('BS', 'Bahamas', 'Bahamas'),
('BT', 'Bhoutan', 'Bhutan'),
('BV', 'Île Bouvet', 'Bouvet Island'),
('BW', 'Botswana', 'Botswana'),
('BY', 'Biélorussie', 'Belarus'),
('BZ', 'Belize', 'Belize'),
('CA', 'Canada', 'Canada'),
('CC', 'Îles Cocos', 'Cocos (Keeling) Islands'),
('CD', 'République Démocratique du Congo', 'Congo, The Democratic Republic of the'),
('CF', 'République Centrafricaine', 'Central African Republic'),
('CG', 'Congo', 'Congo'),
('CH', 'Suisse', 'Switzerland'),
('CI', 'Côte d\'Ivoire', 'Côte d\'Ivoire'),
('CK', 'Îles Cook', 'Cook Islands'),
('CL', 'Chili', 'Chile'),
('CM', 'Cameroun', 'Cameroon'),
('CN', 'Chine', 'China'),
('CO', 'Colombie', 'Colombia'),
('CR', 'Costa Rica', 'Costa Rica'),
('CU', 'Cuba', 'Cuba'),
('CV', 'Cap-Vert', 'Cape Verde'),
('CW', 'Curaçao', 'Curaçao'),
('CX', 'Île Christmas', 'Christmas Island'),
('CY', 'Chypre', 'Cyprus'),
('CZ', 'République Tchèque', 'Czech Republic'),
('DE', 'Allemagne', 'Germany'),
('DJ', 'Djibouti', 'Djibouti'),
('DK', 'Danemark', 'Denmark'),
('DM', 'Dominique', 'Dominica'),
('DO', 'République Dominicaine', 'Dominican Republic'),
('DZ', 'Algérie', 'Algeria'),
('EC', 'Équateur', 'Ecuador'),
('EE', 'Estonie', 'Estonia'),
('EG', 'Égypte', 'Egypt'),
('EH', 'Sahara Occidental', 'Western Sahara'),
('ER', 'Érythrée', 'Eritrea'),
('ES', 'Espagne', 'Spain'),
('ET', 'Éthiopie', 'Ethiopia'),
('FI', 'Finlande', 'Finland'),
('FJ', 'Fidji', 'Fiji'),
('FK', 'Îles Malouines', 'Falkland Islands (Malvinas)'),
('FM', 'Micronésie', 'Micronesia, Federated States of'),
('FO', 'Îles Féroé', 'Faroe Islands'),
('FR', 'France', 'France'),
('GA', 'Gabon', 'Gabon'),
('GB', 'Royaume-Uni', 'United Kingdom'),
('GD', 'Grenade', 'Grenada'),
('GE', 'Géorgie', 'Georgia'),
('GF', 'Guyane Française', 'French Guiana'),
('GG', 'Guernesey', 'Guernsey'),
('GH', 'Ghana', 'Ghana'),
('GI', 'Gibraltar', 'Gibraltar'),
('GL', 'Groenland', 'Greenland'),
('GM', 'Gambie', 'Gambia'),
('GN', 'Guinée', 'Guinea'),
('GP', 'Guadeloupe', 'Guadeloupe'),
('GQ', 'Guinée Équatoriale', 'Equatorial Guinea'),
('GR', 'Grèce', 'Greece'),
('GS', 'Géorgie du Sud et les Îles Sandwich du Sud', 'South Georgia and the South Sandwich Islands'),
('GT', 'Guatemala', 'Guatemala'),
('GU', 'Guam', 'Guam'),
('GW', 'Guinée-Bissau', 'Guinea-Bissau'),
('GY', 'Guyana', 'Guyana'),
('HK', 'Hong Kong', 'Hong Kong'),
('HM', 'Îles Heard-et-MacDonald', 'Heard Island and McDonald Islands'),
('HN', 'Honduras', 'Honduras'),
('HR', 'Croatie', 'Croatia'),
('HT', 'Haïti', 'Haiti'),
('HU', 'Hongrie', 'Hungary'),
('ID', 'Indonésie', 'Indonesia'),
('IE', 'Irlande', 'Ireland'),
('IL', 'Israël', 'Israel'),
('IM', 'Île de Man', 'Isle of Man'),
('IN', 'Inde', 'India'),
('IO', 'Territoire Britannique de l\'Océan Indien', 'British Indian Ocean Territory'),
('IQ', 'Irak', 'Iraq'),
('IR', 'Iran', 'Iran, Islamic Republic of'),
('IS', 'Islande', 'Iceland'),
('IT', 'Italie', 'Italy'),
('JE', 'Jersey', 'Jersey'),
('JM', 'Jamaïque', 'Jamaica'),
('JO', 'Jordanie', 'Jordan'),
('JP', 'Japon', 'Japan'),
('KE', 'Kenya', 'Kenya'),
('KG', 'Kirghizistan', 'Kyrgyzstan'),
('KH', 'Cambodge', 'Cambodia'),
('KI', 'Kiribati', 'Kiribati'),
('KM', 'Comores', 'Comoros'),
('KN', 'Saint-Kitts-et-Nevis', 'Saint Kitts and Nevis'),
('KP', 'Corée du Nord', 'Korea, Democratic People\'s Republic of'),
('KR', 'Corée du Sud', 'Korea, Republic of'),
('KW', 'Koweït', 'Kuwait'),
('KY', 'Îles Caïmans', 'Cayman Islands'),
('KZ', 'Kazakhstan', 'Kazakhstan'),
('LA', 'Laos', 'Lao People\'s Democratic Republic'),
('LB', 'Liban', 'Lebanon'),
('LC', 'Sainte-Lucie', 'Saint Lucia'),
('LI', 'Liechtenstein', 'Liechtenstein'),
('LK', 'Sri Lanka', 'Sri Lanka'),
('LR', 'Libéria', 'Liberia'),
('LS', 'Lesotho', 'Lesotho'),
('LT', 'Lituanie', 'Lithuania'),
('LU', 'Luxembourg', 'Luxembourg'),
('LV', 'Lettonie', 'Latvia'),
('LY', 'Libye', 'Libya'),
('MA', 'Maroc', 'Morocco'),
('MC', 'Monaco', 'Monaco'),
('MD', 'Moldavie', 'Moldova, Republic of'),
('ME', 'Monténégro', 'Montenegro'),
('MF', 'Saint-Martin', 'Saint Martin (French part)'),
('MG', 'Madagascar', 'Madagascar'),
('MH', 'Îles Marshall', 'Marshall Islands'),
('MK', 'Macédoine', 'North Macedonia'),
('ML', 'Mali', 'Mali'),
('MM', 'Myanmar', 'Myanmar'),
('MN', 'Mongolie', 'Mongolia'),
('MO', 'Macao', 'Macao'),
('MP', 'Îles Mariannes du Nord', 'Northern Mariana Islands'),
('MQ', 'Martinique', 'Martinique'),
('MR', 'Mauritanie', 'Mauritania'),
('MS', 'Montserrat', 'Montserrat'),
('MT', 'Malte', 'Malta'),
('MU', 'Maurice', 'Mauritius'),
('MV', 'Maldives', 'Maldives'),
('MW', 'Malawi', 'Malawi'),
('MX', 'Mexique', 'Mexico'),
('MY', 'Malaisie', 'Malaysia'),
('MZ', 'Mozambique', 'Mozambique'),
('NA', 'Namibie', 'Namibia'),
('NC', 'Nouvelle-Calédonie', 'New Caledonia'),
('NE', 'Niger', 'Niger'),
('NF', 'Île Norfolk', 'Norfolk Island'),
('NG', 'Nigeria', 'Nigeria'),
('NI', 'Nicaragua', 'Nicaragua'),
('NL', 'Pays-Bas', 'Netherlands'),
('NO', 'Norvège', 'Norway'),
('NP', 'Népal', 'Nepal'),
('NR', 'Nauru', 'Nauru'),
('NU', 'Niue', 'Niue'),
('NZ', 'Nouvelle-Zélande', 'New Zealand'),
('OM', 'Oman', 'Oman'),
('PA', 'Panama', 'Panama'),
('PE', 'Pérou', 'Peru'),
('PF', 'Polynésie Française', 'French Polynesia'),
('PG', 'Papouasie-Nouvelle-Guinée', 'Papua New Guinea'),
('PH', 'Philippines', 'Philippines'),
('PK', 'Pakistan', 'Pakistan'),
('PL', 'Pologne', 'Poland'),
('PM', 'Saint-Pierre-et-Miquelon', 'Saint Pierre and Miquelon'),
('PN', 'Pitcairn', 'Pitcairn'),
('PR', 'Porto Rico', 'Puerto Rico'),
('PS', 'Territoire Palestinien', 'Palestine, State of'),
('PT', 'Portugal', 'Portugal'),
('PW', 'Palaos', 'Palau'),
('PY', 'Paraguay', 'Paraguay'),
('QA', 'Qatar', 'Qatar'),
('RE', 'Réunion', 'Réunion'),
('RO', 'Roumanie', 'Romania'),
('RS', 'Serbie', 'Serbia'),
('RU', 'Russie', 'Russian Federation'),
('RW', 'Rwanda', 'Rwanda'),
('SA', 'Arabie Saoudite', 'Saudi Arabia'),
('SB', 'Salomon', 'Solomon Islands'),
('SC', 'Seychelles', 'Seychelles'),
('SD', 'Soudan', 'Sudan'),
('SE', 'Suède', 'Sweden'),
('SG', 'Singapour', 'Singapore'),
('SH', 'Sainte-Hélène, Ascension et Tristan da Cunha', 'Saint Helena, Ascension and Tristan da Cunha'),
('SI', 'Slovénie', 'Slovenia'),
('SJ', 'Svalbard et Jan Mayen', 'Svalbard and Jan Mayen'),
('SK', 'Slovaquie', 'Slovakia'),
('SL', 'Sierra Leone', 'Sierra Leone'),
('SM', 'Saint-Marin', 'San Marino'),
('SN', 'Sénégal', 'Senegal'),
('SO', 'Somalie', 'Somalia'),
('SR', 'Suriname', 'Suriname'),
('SS', 'Soudan du Sud', 'South Sudan'),
('ST', 'Sao Tomé-et-Principe', 'Sao Tome and Principe'),
('SV', 'El Salvador', 'El Salvador'),
('SX', 'Saint-Martin', 'Sint Maarten (Dutch part)'),
('SY', 'Syrie', 'Syrian Arab Republic'),
('SZ', 'Eswatini', 'Eswatini'),
('TC', 'Îles Turks-et-Caïques', 'Turks and Caicos Islands'),
('TD', 'Tchad', 'Chad'),
('TF', 'Terres Australes Françaises', 'French Southern Territories'),
('TG', 'Togo', 'Togo'),
('TH', 'Thaïlande', 'Thailand'),
('TJ', 'Tadjikistan', 'Tajikistan'),
('TK', 'Tokelau', 'Tokelau'),
('TL', 'Timor-Leste', 'Timor-Leste'),
('TM', 'Turkménistan', 'Turkmenistan'),
('TN', 'Tunisie', 'Tunisia'),
('TO', 'Tonga', 'Tonga'),
('TR', 'Turquie', 'Turkey'),
('TT', 'Trinité-et-Tobago', 'Trinidad and Tobago'),
('TV', 'Tuvalu', 'Tuvalu'),
('TW', 'Taïwan', 'Taiwan, Province of China'),
('TZ', 'Tanzanie', 'Tanzania, United Republic of'),
('UA', 'Ukraine', 'Ukraine'),
('UG', 'Ouganda', 'Uganda'),
('UM', 'Îles Mineures Éloignées des États-Unis', 'United States Minor Outlying Islands'),
('US', 'États-Unis', 'United States'),
('UY', 'Uruguay', 'Uruguay'),
('UZ', 'Ouzbékistan', 'Uzbekistan'),
('VA', 'Vatican', 'Holy See (Vatican City State)'),
('VC', 'Saint-Vincent-et-les Grenadines', 'Saint Vincent and the Grenadines'),
('VE', 'Venezuela', 'Venezuela, Bolivarian Republic of'),
('VG', 'Îles Vierges Britanniques', 'Virgin Islands, British'),
('VI', 'Îles Vierges des États-Unis', 'Virgin Islands, U.S.'),
('VN', 'Vietnam', 'Viet Nam'),
('VU', 'Vanuatu', 'Vanuatu'),
('WF', 'Wallis-et-Futuna', 'Wallis and Futuna'),
('WS', 'Samoa', 'Samoa'),
('YE', 'Yémen', 'Yemen'),
('YT', 'Mayotte', 'Mayotte'),
('ZA', 'Afrique du Sud', 'South Africa'),
('ZM', 'Zambie', 'Zambia'),
('ZW', 'Zimbabwe', 'Zimbabwe');

CREATE TABLE IF NOT EXISTS movies (
    id INT AUTO_INCREMENT PRIMARY KEY,
    adult BOOLEAN,
    tmdb_id VARCHAR(255),
    imdb_id VARCHAR(255),
    original_language VARCHAR(255),
    title VARCHAR(255),
    slug VARCHAR(255),
    original_title VARCHAR(255),
    overview TEXT,
    release_date DATE,
    runtime INT,
    vote_average FLOAT,
    vote_count INT,
    actors TEXT,
    directors TEXT,
    producers TEXT,
    genres TEXT,
    trailer VARCHAR(255),
    poster_path VARCHAR(255),
    backdrop_path VARCHAR(255),
    belongs_to_collection_id INT,
    belongs_to_collection_name VARCHAR(255),
    belongs_to_collection_poster_path VARCHAR(255),
    belongs_to_collection_backdrop_path VARCHAR(255),
    price DECIMAL(10, 2),
    visited INT DEFAULT 0
);


CREATE TABLE stars (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    slug VARCHAR(255) NOT NULL UNIQUE
);



CREATE TABLE IF NOT EXISTS genres (
    id INT AUTO_INCREMENT PRIMARY KEY,
    tmdb_genre_id INT,
    name_fr VARCHAR(255),
    name_en VARCHAR(255)
);

INSERT INTO genres (tmdb_genre_id, name_fr, name_en) VALUES
(28, 'Action', 'Action'),
(12, 'Aventure', 'Adventure'),
(16, 'Animation', 'Animation'),
(35, 'Comédie', 'Comedy'),
(80, 'Crime', 'Crime'),
(99, 'Documentaire', 'Documentary'),
(18, 'Drame', 'Drama'),
(10751, 'Familial', 'Family'),
(14, 'Fantastique', 'Fantasy'),
(36, 'Histoire', 'History'),
(27, 'Horreur', 'Horror'),
(10402, 'Musique', 'Music'),
(9648, 'Mystère', 'Mystery'),
(10749, 'Romance', 'Romance'),
(878, 'Science-Fiction', 'Science Fiction'),
(10770, 'Téléfilm', 'TV Movie'),
(53, 'Thriller', 'Thriller'),
(10752, 'Guerre', 'War'),
(37, 'Western', 'Western');






CREATE TABLE IF NOT EXISTS clients (
    id INT PRIMARY KEY AUTO_INCREMENT,
    firstname VARCHAR(255),
    lastname VARCHAR(255),
    date_of_birth DATE,
    subscription_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    email VARCHAR(255),
    pass VARCHAR(255),
    isAdmin BOOLEAN DEFAULT false
);


CREATE TABLE IF NOT EXISTS addresses (
    id INT PRIMARY KEY AUTO_INCREMENT,
    client_id INT,
    firstname VARCHAR(255),
    lastname VARCHAR(255),
    address_number VARCHAR(255),
    complement VARCHAR(255),
    address VARCHAR(255),
    postal_code VARCHAR(255),
    town VARCHAR(255),
    type_of_address VARCHAR(255),
    FOREIGN KEY (client_id) REFERENCES clients(id)
);

CREATE TABLE IF NOT EXISTS status (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255)
);

INSERT INTO status (id, name) VALUES (1, 'En attente');
INSERT INTO status (id, name) VALUES (2, 'Validé');
INSERT INTO status (id, name) VALUES (3, 'Expédié');


CREATE TABLE IF NOT EXISTS orders (
    id INT PRIMARY KEY AUTO_INCREMENT,
    client_id INT,
    order_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    address VARCHAR(255),
    number_of_articles INT,
    total_price_htc DECIMAL(10, 2),
    total_price_ttc DECIMAL(10, 2),
    status_id INT,
    FOREIGN KEY (client_id) REFERENCES clients(id),
    FOREIGN KEY (status_id) REFERENCES status(id)
);


CREATE TABLE IF NOT EXISTS order_details (
    id INT PRIMARY KEY AUTO_INCREMENT,
    order_id INT,
    movie_id INT,
    quantity INT,
    unit_price_htc DECIMAL(10, 2),
    tva DECIMAL(5, 2),
    unit_price_ttc DECIMAL(10, 2),
    FOREIGN KEY (order_id) REFERENCES orders(id),
    FOREIGN KEY (movie_id) REFERENCES movies(id)
);

CREATE TABLE IF NOT EXISTS tva (
    id INT PRIMARY KEY AUTO_INCREMENT,
    rate DECIMAL(5,2) NOT NULL DEFAULT 20.00
);

INSERT INTO tva (rate)
VALUES (20.00);











CREATE TABLE roles (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

INSERT INTO roles (name) VALUES ('actor'), ('director'), ('producer');

CREATE TABLE movies_stars_roles (
    movie_id INT,
    star_id INT,
    role_id INT,
    PRIMARY KEY (movie_id, star_id, role_id),
    FOREIGN KEY (movie_id) REFERENCES movies(id),
    FOREIGN KEY (star_id) REFERENCES stars(id),
    FOREIGN KEY (role_id) REFERENCES roles(id)
);